- chapter_15.asciidoc
A tiny, innocuous suggestion.
My git-diff shows an unexpected '^M' in the change, but I think my line-endings are all kosher. You're using DOS line endings, right? That's what my vim tells me it's saving, and a hex editor says my change has the same line ending as all the other lines, so I think I'm good.
> ch15: explain de-spike

- asciidoctor.css
- chapter_16.asciidoc
I think it's helpfully more specific to say that 'our test' is doing
the mocking, rather than 'we're asking Python to' do it. YMMV
> minor rewording suggestion

- chapter_manual_deployment.asciidoc
Django 1.11.5 is invalid, side effect of bulk updating. :wink: 
Changed it into 1.11.b1
> Change Django version in requirements.txt

- chapter_server_side_debugging.asciidoc
replaced the first occurrence of 'little story' with 'a'
> 'little story' was repeated

- chapter_working_incrementally.asciidoc
'in' should appear between 'it' and 'our' on line 1922
> Missing word 'in'

- chapter_simple_form.asciidoc
...Django has add the... -> ...Django has added the...
> Typo in A Simple Form chapter

- chapter_01.asciidoc
> changed "unapplied migrations" message

- chapter_page_pattern.asciidoc
In chapter 25 we start using the Page object to rewrite our test. This line was in the first code example and wasn't in the second. It's a little confusing because it seems like we can delete it but it will be a mistake.
> Add missing line of code in example of Chapter 25

- preface.asciidoc
> preface typo

- chapter_post_and_database.asciidoc
- chapter_unit_test_first_view.asciidoc
- chapter_working_incrementally.asciidoc
I was trying to put only the last commit in here, but I didn't do it right. I apologize for the duplication in my two pull requests. I am still figuring out how Git and Github work.
> Chapter 7 - small revision for accuracy

- server-quickstart.md
Fix typos errors described in issue #131.
> Fix typos in server-quickstart.md file

- pre-requisite-installations.asciidoc
- change single quoted 'and' -s to italic
- add notes on installing pyenv
- update virtualenv directory name to .venv
- add notes on different pip install output
- update ImportError message
- update tdd-python-book to goat-book
> review pre-requisite-installations

- pre-requisite-installations.asciidoc
Looks generally good. I ran through the instructions on my Mac with no problem (though of course I did have Python, git etc. installed).
I kind of wish there was a website which just captured the current getting Python running basics so every Python book ever didn't need to figure this stuff out 😄
> Review of pre-requisites

- chapter_01.asciidoc
Great chapter. Just need to update the test for the version of Django they'll have installed. Otherwise everything worked for me.
> Review Chapter 1

- pre-requisite-installations.asciidoc
Add 2 suggestions:
- About Note on IDEs
- About locking Selenuim version
> Review pre-requisite-installations.asciidoc

- chapter_02_unittest.asciidoc
I like the Minimum Viable Product being mentioned. It further shows how closely related good product management practices and good software development practices are.
Other than adding one more commit right before introducing `unittest.TestCase`, I don't feel like anything should be changed about this chapter.
> review  chapter_02

- chapter_philosophy_and_refactoring.asciidoc
I haven't found much to change about this chapter. Felt refreshingly smooth after the previous, longer one. I like the new flowcharts!
> review chapter Philosophy and Refactoring

- chapter_02_unittest.asciidoc
Brian Okken wrote second edition of "Python Testing with pytest". I have updated the link to the new book
> Update link to 2nd edition of Pytest book

- chapter_philosophy_and_refactoring.asciidoc
- Add note about FT abbreviation
- Add note about assertTemplateUsed test
> Review chapter_philosophy_and_refactoring.asciidoc

- chapter_unit_test_first_view.asciidoc
Overall, this was a pretty long chapter, but I don't think it would make sense to split into maybe two smaller ones.
> review  chapter_unit_test_first_view

- chapter_02_unittest.asciidoc
Everything worked for me.
Really enjoying it so far, I like the feeling that we're pair-programming.
> Comments on Chapter 2

- chapter_philosophy_and_refactoring.asciidoc
Really enjoyed the discussion here.
As mentioned in one of my comments, I wonder if it's worth digging a bit more into where the division of unit vs functional tests is here. In practice I would say the functional test is good enough for testing the url routing.
> Review philosophy chapter

- pre-requisite-installations.asciidoc
Hey 👋 Nice intro to many basic tools necessary for software development with Python.
I'm well aware this book is mostly an update & extension of previous versions, but I wonder if focusing solely on Django is the best idea.
Microframeworks are now on the rise (at least in my information buble). I think it could be valuable to also somehow mention how to apply pieces of advice here and there to other frameworks.
> Feedback on prerequisites chapter & small typo fix

- chapter_explicit_waits_1.asciidoc
Other than the updating of Selenium isn't directly related to this chapter, I didn't find anything I would change about this chapter. Fast, short, concise.
> review explicit waits

- chapter_01.asciidoc
This a good, baby step for ensuring everything is running as it should before the following chapters.
Unfortunately, the code example is not working anymore. At least two people before me and I already noticed that, though.
> Add comments for chapter 01

- chapter_02_unittest.asciidoc
I left a few comments in the chapter body.
> Review of chapter 02

- chapter_unit_test_first_view.asciidoc
Informative intro to unit tests of a single view function, can't wait for the next chapter. 
Left a few comments in the body, mostly about the completeness of code snippets and one about comparing unit vs functional tests.
> Review of chapter 03

- chapter_post_and_database.asciidoc
Another round of review from me.
Out of curiosity (I'm not a native English speaker) - what's with using "her" pronoun when gender is unknown? I only know about using they/them in such a situation.
I'm talking about a sentence that ends the first paragraph:
> so that we can save it somehow and display it back to her later
This chapter is quite long and reviewing it was a bit exhausting. Is there an option perhaps to split it somehow? Or put some summary in the middle to let a reader catch a breath?
> Review of chapter chapter_post_and_database.asciidoc

- chapter_philosophy_and_refactoring.asciidoc
Just added two comments. Overall, nice chapter.
> Review of chapter chapter_philosophy_and_refactoring.asciidoc

- chapter_working_incrementally.asciidoc
> Review chapter_working_incrementally.asciidoc

- chapter_working_incrementally.asciidoc
Another round of review from me.
Really liked this chapter as it lets to experience what it feels like to be a TDDer first-hand.
Added just a few slight comments to provide more context in one or two places. The only constructive feedback I have is for testing context passed to `render` function.
> Review of chapter chapter_working_incrementally.asciidoc

- chapter_07_working_incrementally.asciidoc
I enjoyed this chapter very much, but I found myself disagreeing a bit more with some of the approaches. All opinion-based though!
In particular, I feel like we're rather divorced from actually using the application. I have seen developers focus too much on the tests and never actually try using what they're building, and they end up shipping things that don't actually work. IMO it would be helpful to encourage the occasional return to trying it out as a user, especially when debugging FTs.
If we were to do that, as I was, we would need to address handling the addition of the non-nullable foreign key to the model. I ran into problems running migrations in my local database because there were already items in there. Have left a comment with a suggestion on that.
I also feel that some of …
> Review working incrementally

- chapter_08_prettification.asciidoc
- Suggest to mention force refresh for browser
- Suggest to briefly describe StaticLiveServerTestCase
> Review chapter_08_prettification.asciidoc

- chapter_08_prettification.asciidoc
It was a fun and dynamic chapter to read, and I wasn't bored even for a moment.
It's very cool that you introduced Bootstrap in a simple, non-intrusive way. 
Aaaand mentioning dark mode was like getting candy out of the blue - unexpected, but very much appreciated!
I've got a few comments regarding TDD cycle and clarity of troubleshooting the issue with non-loading CSS.
> Comments to chapter 8

- README.md
Related to https://github.com/hjwp/Book-TDD-Web-Dev-Python/commit/e0b32d217bfdad39af4367ad831cb765e1f2d24c
> update README pip install command

- chapter_10_production_readiness.asciidoc
One general comment: The Dockerfile at the end of the chapter is far from production-ready. e.g., the root user is used to run the server, etc. I'd suggest you check [Dockerizing Django with Postgres, Gunicorn, and Nginx](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/) and [Docker Best Practices for Python Developers](https://testdriven.io/blog/docker-best-practices/#prefer-array-over-string-syntax). I don't think you should go into details, but IMO it would be beneficial to have an actual production-ready Docker image at the end of the chapter. People usually take things they find in courses and books as they are and use them in production. Especially the deployment-related things - "It works. Let's just use it".
> Review chapter_10_production_readiness.asciidoc

- chapter_10_production_readiness.asciidoc
This chapter was much lighter than chapter 9th, but still very relevant.
Those summaries, especially "Production-Readiness Config" are great. They provide a checklist-like guide for people not to get lost and are nice to see at the end of the chapter.
I am not very fond of freezing just "top-level" dependencies of the project, as it is shown in the chapter. This is not guaranteeing the reproducible builds and I failed to build & deploy because of that more than once. But I understand it's a trade-off so the reader does get bogged down.
Apart from that, one suggestion about linking Django docs page for deployment for curious readers.
> Review of chapter 10

- chapter_09_docker.asciidoc
As Rita asked, I had another look on this chapter and found a few more minor things. I was trying not to repeat myself but I just noticed I did with the non-privileged user in the Docker container - suggestion. 
Overall, I like the improvements!
> review chapter09 (rev2)

- chapter_12_organising_test_files.asciidoc
I ended up doing both an update and review of Chapter 12. I found all code examples were up to date and working and I couldn't find any best practices or tips that were outdated either.
I added a few suggestions and edits. 
I ended up not committing a comment at line 669, but I still wanted mention that adding new lines describing further test scenarios before we make the first one pass feels less ~~right~~ comfortable. But it isn't bad, just something I noticed.
It was a faster, shorter chapter; easy to follow and it was nice to see the growing test files end up split up into their corresponding files.
> Update chapter 12

- chapter_10_production_readiness.asciidoc
There are three fixes on this PR:
1. #225
2. #226 
3. I also noticed `ch10l005` commit ref was actually written as `ch09l005` which is now fixed
> Minor chapter 10 asciidoc fixes

- chapter_10_production_readiness.asciidoc
- chapter_11_ansible.asciidoc
I like this chapter, as it touches on a few things I'm less comfortable with. There are a few things to be ironed out though.
The main challenge is that I found that when I ran into problems I lacked the mental model to troubleshoot - it's possible that others who don't have access to Harry(TM) will give up. I think talking through what Ansible is doing, maybe even a diagram at the beginning of the chapter to show what we're aiming for? In particular, it's difficult to understand where the Ansible error logs are coming from (i.e. local, server, container...)
I also think we're missing some stuff at the end about how all this might look as a development workflow. Maybe talk about setting up scripts (so we don't have to remember the ansible command?) And what about releasing to production? …
> Review Ansible chapter

- chapter_09_docker.asciidoc
- chapter_11_ansible.asciidoc
- server-quickstart.md
Due to some errors after resolving merge conflicts, I decided to open a new PR for this. Original PR: https://github.com/hjwp/Book-TDD-Web-Dev-Python/pull/215
We forgot to lead the reader where to make `git commit`s in the chapter. Also, I would consider adding an ansible config file once we got all the options `ansible-playbook` command needs, so the command is shorter. Otherwise, I found the the approach, and the length of this chapter good.
> Review  chapter 11 ansible

- chapter_08_prettification.asciidoc
- chapter_09_docker.asciidoc
This pull request proposes a few small edits for chapters 8 and 9. Each of the edits is independent of the others. I can edit/revert any commit deemed incorrect/unwarranted. 
For each commit, the commit message gives more info. 
Please share any questions, and it won't hurt my feelings if edits are denied.
> chapters 8 and 9: propose a few small edits

- chapter_12_organising_test_files.asciidoc
Solid chapter, good reminder that we should apply the same standards of quality to our test code as to our application code.
> Review Chapter 12

- chapter_13_database_layer_validation.asciidoc
@ritaf-ORM for some reason I can't select your username for requesting review, so I'll just @ tag you.
> Re: Rita review on chapter 13

- chapter_14_simple_form.asciidoc
add TODO to reorder steps
mention pycache
remove chapter update warning
add commit at the end of the chapter
> some additions to chapter14

- .gitmodules
- Makefile
- appendix_IV_testing_migrations.asciidoc
- appendix_github_links.asciidoc
- atlas.json
- book.asciidoc
- chapter_15_advanced_forms.asciidoc
- chapter_17_second_deploy.asciidoc
- preface.asciidoc
- rename-chapter.sh
- tests/chapters.py
- tests/test_book_tester.py
- tests/test_chapter_spiking_custom_auth.py
- todos.txt
- **todos**
- **Rename chapter 17**
> Rename chapter 17

- .gitmodules
- Makefile
- appendix_IV_testing_migrations.asciidoc
- appendix_github_links.asciidoc
- atlas.json
- book.asciidoc
- chapter_15_advanced_forms.asciidoc
- chapter_17_second_deploy.asciidoc
- chapter_18_spiking_custom_auth.asciidoc
- chapter_outside_in.asciidoc
- preface.asciidoc
- rename-chapter.sh
- tests/chapters.py
- tests/test_book_tester.py
- tests/test_chapter_18_spiking_custom_auth.py
- tests/test_chapter_mocking.py
- tests/test_chapter_spiking_custom_auth.py
- todos.txt
- **todos**
- **Rename chapter 17**
- **Rename chapter 18**
> Rename chapter 18

- chapter_15_advanced_forms.asciidoc
- chapter_16_javascript.asciidoc
- pygments-default.css
This branch is based on the WIP `chapter-15-tests` https://github.com/hjwp/Book-TDD-Web-Dev-Python/pull/264
> Chapter15  fix tests

- chapter_11_ansible.asciidoc
- chapter_17_second_deploy.asciidoc
- **start on 17/18**
- **rewrites in 17**
> Chapter 17 minimal update

- chapter_16_javascript.asciidoc
I'm not a JS/TS/Frontend expert, so my review here is scarce.
I enjoyed reading this chapter. Assumptions made (e.g. Jasmine and testing scenarios) seem reasonable. Plus additional knowledge about JavaScript sneaked in. I think it's nice to see how concepts of testing apply in this new context, hope it will help some readers to remember and learn the principles!
> Review of chapter 16

- .github/workflows/tests.yml
- **print firefox and geckodriver version**
- **try removing default firefox**
- **remove firefox with purge**
- **show more info on installed firefox-esr**
- **symlink firefox in**
- **find out where geckodriver is coming from**
- **just kill geckdriver**
> fix geckodriver2

- chapter_13_database_layer_validation.asciidoc
Good chapter, mostly small comments. But I do wonder if framing this as 'testing at the database layer' is a good description of what we're doing. Database layer validation would involve running SQL I think.
> Review by David Seddon of database layer validation

- chapter_14_simple_form.asciidoc
This is an enjoyable chapter that's half about Django's [Model]Form and half about testing.
I had fun reading it. I found very little things to complain about.
One bigger thing is that I'd put at the beginning something to set the expectations and do a little priming of the reader - that we're indeed gonna do be doing some refactor and in such a case functional tests shield us.
Even though we had to make some changes, it was only adjusting details here and there. Behaviour did not change even though we refactored significant amount of code and logic to leverage ModelForm
> Review of chapter 14

- chapter_09_docker.asciidoc
Thanks for a good read, Harry!
Added some in-line comments for chapter 9.
> Add comments on chapter 9

- .gitmodules
- Makefile
- appendix_IX_cheat_sheet.asciidoc
- appendix_I_PythonAnywhere.asciidoc
- appendix_bdd.asciidoc
- appendix_github_links.asciidoc
- appendix_purist_unit_tests.asciidoc
- appendix_rest_api.asciidoc
- atlas.json
- book.asciidoc
- chapter_06_explicit_waits_1.asciidoc
- chapter_12_organising_test_files.asciidoc
- chapter_23_CI.asciidoc
- chapter_24_page_pattern.asciidoc
- chapter_25_hot_lava.asciidoc
- chapter_hot_lava.asciidoc
- epilogue.asciidoc
- preface.asciidoc
- tests/chapters.py
- tests/test_appendix_rest_api.py
- tests/test_chapter_23_CI.py
- tests/test_chapter_24_page_pattern.py
- tests/test_chapter_page_pattern.py
- **Rename CI to chapter_23_CI**
- **Rename chapter page pattern to chapter_24_...**
- **Rename chapter 25 hot lava**
> Rename all remaining chapters

- chapter_17_second_deploy.asciidoc
There is not much content in this chapter which actually... is a good thing here.
It shows one specific, yet crucial thing - [semi-manual] deployment pipeline with testing in staging before deployment to production.
It's great that potential issues with migrations are mentioned and some solutions for staging are shown.
I was a bit surprised by tagging the release part. So far I understood it differently - to put a tag onto a new about-to-be-released version of the application, not specifically tagging what was deployed when and what is currently live. Although, the thing that is presented makes sense.
> Review of chapter 17

- chapter_15_advanced_forms.asciidoc
- chapter_16_javascript.asciidoc
- chapter_18_spiking_custom_auth.asciidoc
- source/push-back.sh
- tests/test_chapter_16_javascript.py
cf https://github.com/hjwp/Book-TDD-Web-Dev-Python/issues/314
- **missing word in 15**
- **several fixes incl missing semicolons in 16**
- **Several more fixes in 16 mostly semicolons, update submodule**
> Address artGonza errata (#314)

- Makefile
- chapter_24_page_pattern.asciidoc
- **start on chap 24**
- **more on 24**
> Update chap 24 page pattern

- chapter_18_spiking_custom_auth.asciidoc
> Practice pull request

- chapter_18_second_deploy.asciidoc
Not much to comment on. The chapter is brief and to the point.
I added a single comment suggesting giving an example of migration that is not compatible with existing data, but that's not a showstopper.
> Review of chapter 18

- chapter_23_debugging_prod.asciidoc
Nice one. I particularly liked the discussion of when to choose _not_ to test something, in this case email.
I do think we should talk a little more about security here - readers should adopt a security mindset when doing things like this and make sure they think things through.
Note: I wasn't able to run the ansible commands as my Digital Ocean account has expired.
> Review of debugging prod

- chapter_26_page_pattern.asciidoc
The format of this chapter works really well!
I wonder if there is a way of introducing some of this earlier in the book in two or three places, maybe in smaller ways. They could commit beforehand and then try to solve certain problems on their own, then undoing their work afterwards and replacing it with how you did it.
> Review page pattern

- chapter_24_outside_in.asciidoc
Very nice explanation on outside-in vs inside-out testing. I mentioned in a comment that maybe a simple sketching of what we want to see on the UI could be helpful before we get to write Functional Tests. This didn't occur to me in earlier chapters, which make sense - while initially every instruction about what the UI should look like was clear, as the UI gets more complex, it may be more difficult to clearly express it in just writing. Not crucial, but I think it would be nice.
At the second part of the chapter, where we introduce the `owner` and then we move on with a failing test, I think we could have used a bit of a demonstration for a hybrid approach: by default we do outside-in, but in some cases it is perfectly fine to do some inside-out. Especially in the `test_views.py` where …
> Csanád's review of chapter 24

- Makefile
- chapter_09_docker.asciidoc
- chapter_10_production_readiness.asciidoc
- chapter_12_ansible.asciidoc
- tests/book_parser.py
- tests/book_tester.py
- tests/sourcetree.py
- tests/test_chapter_10_production_readiness.py
Switch to `USER nonroot`.  required lots of fiddly changes to the `db.sqlite3` file mounting and permissions.  but it works!
> Switch to nonroot user in Docker

- chapter_25_CI.asciidoc
> Review chapter 25
