chapter_12.asciidoc
This small issue prevented the subheading to render properly, see screenshot below:
Thanks for the book, it's very nice!
=> ch12: fix subheading

chapter_15.asciidoc
Also delete a paragraph about mocking, since all the
content on mocking has been move to the next chapter.
=> Fix chapter's final summary box title

chapter_06.asciidoc
This was rendered in HTML as
_\_init__.py
This commit makes it render as
__init__.py (in italics)
which I think is desired.
=> Fix markup of __init__.py

chapter_18.asciidoc
I extended the rant to include other reasons I dislike JSON fixtures.
You might consider the point - not to use them - already sufficiently made, so please ignore this PR if you wish.
=> Extend the rant against JSON fixtures

chapter_mocking.asciidoc
This corrects a small typo in the mocking chapter: there was an extra 'c' in 'accounts'. (Hope this pull request is okay; it's my first. Thanks for writing a great book, btw.)
=> Fix typo: remove extra 'c' in 'acccounts'

chapter_server_side_debugging.asciidoc
systemctl was misspelled  as systemctrl after enabling debugging in gunicorn
=> Fixed typo in systemctl

chapter_post_and_database.asciidoc
In the older text (which didn't make use of the new "f-string" syntax), the assertTrue(...) for the first list item took up six lines. The new notation reduced this to four, and using the assertIn(...) test further reduced it to one.
=> Corrected number of lines replaced with assertIn

chapter_unit_test_first_view.asciidoc
As of Django 1.10.0 django.core.urlresolvers.resolve has been replaced
with django.urls.resolve.
See https://docs.djangoproject.com/en/1.11/ref/urlresolvers/
=> Use from django.urls import resolve

preface.asciidoc
update chapter number scopes of book parts to match the current state as of bab0b9b6993a14f82efecb38f7bc4804f986b2c3
(I've also counted the [Epilogue](http://www.obeythetestinggoat.com/book/epilogue.html), as that is a numbered chapter in the TOC. I didn't count the appendices although the TOC makes it seem as if they blong to part 3, too.)
You might want to check whether the content descriptions of the parts still matches, too. (I've just started reading the book, so I can't know.)
=> update chapter number scopes of book parts

server-quickstart.md
Changes one of the example subdomains to actually be superlists-staging.ottg.eu
=> Fixes typo

chapter_simple_form.asciidoc
Small typo regarding stated number of changes needing to be made vs. actual number of changes to be made in superlists/functional_tests/test_list_item_validation.py
`browser.find_element_by_id('id_new_item')`--> `get_item_input_box()`
see:
https://github.com/hjwp/book-example/blob/860776cd9ed48891e718666acbce0fb97408adbc/functional_tests/test_list_item_validation.py 
vs 
https://github.com/hjwp/book-example/blob/8f656effc2cca885cd1b71db2a7f53272774c1d9/functional_tests/test_list_item_validation.py
=> Update chapter_simple_form.asciidoc (small typo)

chapter_purist_unit_tests.asciidoc
The word 'as' does not belong in the sentence "patch decorators are applied innermost first, so the new mock is injected to our method **as** before the mockNewListForm"
=> Unnecessary 'as'

chapter_making_deployment_production_ready.asciidoc
The footnote in chapter 10 is not rendered correctly ;)
> Hooray, a change that went without a hitch for once!footnote:[If you’re using Fedora/CentOS, you may run into an issue with private tmmp directories. more info here Moving on…​
Thanks again for the great book!
=> typo + missing a "]" in a footnote

chapter_manual_deployment.asciidoc
There is a word missing in the overview for the chapter on "moving to a production-ready config", specifically between "to" and "DEBUG"  in the Security bullet-point. "set" seems like a good fit.
=> Missing word in the overview

server-quickstart.md
Digital ocean droplets have options for configuring block storage, a VPC network, IPv6, user-data, monitoring and back-ups when creating a droplet. These can be ignored (hopefully! I've just ignored them and I've never setup a web server before)
=> user can disregard droplet options

chapter_advanced_forms.asciidoc
When I worked through this chapter, I mistakenly replaced the `save` method from `ItemForm` instead of adding a new `save` method to `ExistingListItemForm`. This PR just makes it clear which class the method belongs to.
=> ch15 clarify that def save(self) is in ExistingListItemForm

chapter_post_and_database.asciidoc, chapter_unit_test_first_view.asciidoc
These edits are intended to add explicit discussions of `import` statements that are changed in the code samples in the book but that are not (now) explicitly called to the reader's attention.
The proposed edits clarify something that confused me as I was working through the book. In the discussion of editing `superlists/urls.py`, there is no explicit mention of changing the `import` statements. In particular, there's no comment in the text about adding the statement `from lists import views`. Without that statement, the tests fail with messages other than those discussed in the book. 
I think I'm like most readers: I assumed that the changes to the source code would be flagged by the writer. Since the only flagged change was to the regular expression for the URL pattern, I didn't think …
=> Suggested edits to Chapter 3 (unit testing) to be explicit about a change to source

chapter_working_incrementally.asciidoc
Marathon chapter, indeed! :) I wouldn't split it up though because the sub-titles help quite a lot with making sensible checkpoints for breaks during reading.
I especially liked when you only shown the expected error messages from the failing tests under Biting the Bullet: Adjusting Our Models.
What do you think about adding an Appendix: Glossary for terms like "Three strikes and refactor" or "Regression test", "YAGNI"?
=> Review  chapter working incrementally

chapter_13_database_layer_validation.asciidoc
The tests here were failing because a couple of changes we made to the listings were not in sync witht he commit history of the branch in the `book-example` repo.  Here's how I fixed things at a high level:
* first, determine that the cause was due to the commits getting out of sync.  I saw the error was that the Fts were failing when the book said they should be passing, and then I see it's at a part of the book where we say "now remove the early return", and I realised we didn't have a commit where we remove the early return.
* I then realised we didn't have a commit for when we *added* the early return either!  that's where we had the commit listing as `ch13l???`.
* so I first added a commit for when we introduce the early return.  I did this by:
1. checkout the chatper 13 branch
2. …
=> Fixes for tests in 13

chapter_14_simple_form.asciidoc
hopefully will get the tests passing.
* the failure was due to the fact that the test runner wraps console output at 80 chars.
* that hid a second failure, which is that when we report `NoSuchElementException`, selenium prints a whole load of carp, that we basically have to hide in the output listings with a trailing `[...]` on the line.
=> Fix a listing in 14

chapter_13_database_layer_validation.asciidoc
It is a rather quick and pretty enjoyable chapter.
There is not much of a constructive feedback from me.
One more serious remark I have is that I got lost when we jumped from Model-level validation to `assertRaises`. I suggest adding some linking sentences.
=> Review of chapter 13

chapter_17_second_deploy.asciidoc
Quick, fast chapter but I found a bug which I mentioned to Harry in a message. We had a discussion whether we should update chapter 11 or include the (short, one-line) solution here.
I'm personally on the opinion to extend the `ansible-playbook.yaml` here in chapter 17, when we notice the bug after running the FTs against the staging server. To me, it feels more natural not to include `force_source` in the "Import container image on server" task until we try to create a second deployment here, in chapter 17 where we notice that somehow the deployed version is old.
As Harry pointed out, some readers may try to deploy their code (therefore also face this bug) sooner. Still, I think we could include the solution in this chapter but mention it in a NOTE in chapter 11.
=> Csanad: review chapter 17

chapter_18_second_deploy.asciidoc
This chapter has been previously reviewed when it was `chapter 17`. I only found a small error: renaming the `ansible-playbook` to `deploy-playbook.yaml` resulted in `deploy-playbook.yaml.yaml`. I re-ran the deployment script just to be sure, but everything looked as expected.
=> Csanád review chapter 18

pre-requisite-installations.asciidoc
Removed link to webplatform.org (discontinued in 2015) and replaced with the new URL webplatform.org redirects to (MDN).
Might make it easy for newer developers to go straight to a free, reputable source
=> Update HTML tutorial link to MDN in pre-requisite-installations.asciidoc

chapter_19_spiking_custom_auth.asciidoc
I like the email-based authentication, even though I had mixed feelings about it initially (not in the book specifically, but about Magic Links in general).
In the "spike" part of the chapter we sometimes take bigger leaps without checking our work, which I found a bit difficult to keep up with at first. Although we can't always check our work step-by-step, and having to re-read a few paragraphs here and there is just how technical books work. Also, practicing to read and make sense of source code is how developers operate. So I would not necessarily change it, I'm just providing my impressions. More importantly, I found it extremely useful: showing the readers the thought process, the sources/docs used for discovering how we could make something (like this custom authentication) work.
A …
=> Csanád's review of chapter 19

chapter_15_simple_form.asciidoc
Good stuff. I like the way you gradually introduce the idea of a form here.
Reviewing this chapter prompted a couple of more general thoughts.
The Selenium-based functional testing approach involves tradeoffs. For me, the lower-level Django test client (or, even better [django-webtest](https://pypi.org/project/django-webtest/)) is a sweeter spot for functional testing. I appreciate we use these in test_views, but they're not really unit tests. I'm not sure whether you get to it later in the book, but I think it would be worthwhile discussing the different options so people don't feel like they absolutely have to use Selenium to have decently tested web applications.
And, more generally - we can't test _everything_, right? So it's about judging the tradeoffs. I think the readers should …
=> Review of simple form chapter

chapter_16_advanced_forms.asciidoc
Looking good. A few small issues that I noticed though.
A general point: I feel like just because we're doing TDD doesn't mean we can't occasionally start up the application and use it to figure out what's happening. It feels like a long time since we've done that!
=> Review of advanced forms chapter

chapter_19_spiking_custom_auth.asciidoc
I like the way in this chapter you give a flavour of what it's like to give something a try without TDD - and then return to it. 
But - of all the chapters I've reviewed so far, I think this would most benefit with some more work. For me, reading the spike comes down to copy-pasting code that isn't really explained, and I don't think feel carried along with your thought process for that part of the chapter. So I think it would work better to move more of the explanation to the spike phase.
It also might work better to conduct the spike a little differently. For example:
- You could start with laying out the high level design, with a sequence diagram.
- Then you could stub out the user interface (without, say, any actual email - it could just print the link out to the terminal). Get us to …
=> Review custom auth

chapter_20_mocking_1.asciidoc
This chapter was mainly easy to follow, although I felt a few words would have helped here and there.
At first, I wanted to move the premature import of `send_mail`, because we haven't really written code we didn't need immediately yet. But after some failed edits, I figured that's still the best place for it; even though the manual monkeypatching would work without the import already there in the `views.py`, it would be less understandable.
=> Csanád - review of chapter 20

chapter_20_mocking_1.asciidoc
I like the pragmatic approach you take to mocking here (especially consider we both know they are BAD!) In particular I think the messages framework is a great way of making the point.
I think a bit more explanation for the Django bits wouldn't go amiss - and as I say in the comment, perhaps even ditch the whole authentication backend for a lower-level approach that uses the session framework directly.
It might also be worth drawing the distinction between mocking and monkeypatching, and the trade offs involved with each. Maybe also some more strongly worded advice against directly monkeypatching attributes in tests without tidying up afterwards.
=> Review of mocking 1

chapter_21_mocking_2.asciidoc
Looks good generally. As mentioned in my review of the previous chapter, mocking and patching are two separate techniques (often used together) and it might be worthwhile discussing their tradeoffs separately.
=> Review of mocks 2

chapter_21_mocking_2.asciidoc
It is a pretty long chapter, full of valuable knowledge and some key considerations, e.g. regarding a number of tests, preventing combinatorial explosion and mocks in general.
Although it reads rather easily, it feels long. While reading the previous chapter, I didn't have that impression.
I guess it's mostly because of finishing up functional tests. I have a feeling the chapter could put a hard stop when we realised the first functional test passes. 
Apart from that, a potentially outdated part about possible typos in mock methods caught my eye. This definitely needs consideration.
=> Review of chapter 21

chapter_22_fixtures_and_wait_decorator.asciidoc
This chapter feels a little short compared to some of the others, but otherwise looks good.
=> Review of decorator chapter

chapter_23_debugging_prod.asciidoc
The pace is, again, just right. Fast, not overly detailed but still easy to follow and answers pretty much all questions one may have. 
Later in the chapter, where we are deploying to the staging environment, I got stuck: `test_my_lists` failed by telling me it could not find `#id_logout`. Since the test ran fine just previously against the local docker, and the deployment is a `.tar` archive, and there may not be sqlite3 client installed by default, it may not be very straightforward to investigate if the reader believes there is a discrepancy between their local docker deployment and the staging.
This got me thinking: maybe we could add a few hints for what to do in case the reader believes there is a bug on staging: trying to reproduce it on the local docker environment and manually …
=> Csanád review of chapter 23

chapter_24_outside_in.asciidoc
This chapter is not the easiest one to read and follow.
I suggested adding some diagrams to visualize layers that we are crossing while doing outside-in TDD.
I would consider removing a part about `@property` or at least discourage readers from doing DB calls inside it.
=> Review of chapter 24

chapter_25_CI.asciidoc
A crucial chapter.
I miss some introduction to what CI actually is and what is its role in today's modern development. Like some sales pitch why readers should care if they are strangers to the concept. Some mentions of team work in a contemporary working environment would be great 👌 
What I noticed is that somewhere in the middle pace changes from quickly getting up to speed with Gitlab CI to tedious debugging.
I think it might use a refreshing perspective AFTER the debugging part to zoom out, sum up what was done, how this could've been avoided and how it works in a modern working environment.  Being able to run all or as many tests as possible locally is great, but _normally_ (my experience, so might be biased) ppl build things from the start to make sure that CI will pass.
=> Review of chapter 25

chapter_25_CI.asciidoc
This is a very useful topic and I agree with the approach. However, I found some inconsistencies in the chapter. Unfortunately, I was unable to spend more time figuring it out, but I tried providing every clue I found relevant.
@hjwp if you need anything else regarding these, just let me know!
Apart from the possible bugs, I think this chapter shows and explains very well how to set up automated CI builds and how to troubleshoot them.
=> Csanád's review of chapter 25

chapter_26_page_pattern.asciidoc
This seemingly shorter chapter is actually quite a challenge (but does **not** give off the vibes of the meme known from college maths textbooks: "the proof is left for the reader as an exercise" :)  especially because the `book-example` repo is always there for cross-checking the work). The hints are very useful and basically showing what to do without revealing the implementation right away.
I agree with the assumption of the reader should be able to test drive this feature on their own by now. And, if they do, it will be a very beneficial experience.
=> Csanád's review of chapter 26
